# -*- coding: utf-8 -*-
"""Interactive Scouting Report LIV-TOT 2019 UCL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rmb23fijhFxTHVn6oxlktkbn7srBYNQA
"""

!pip install statsbombpy mplsoccer

import pandas as pd
import matplotlib.pyplot as plt
from mplsoccer import Pitch
import statsbombpy as sb

# Primero validamos que todo funciona en Colab
from statsbombpy import sb
import pandas as pd
import matplotlib.pyplot as plt
from mplsoccer import Pitch
import warnings
warnings.filterwarnings('ignore')

# Cargar datos del partido
eventos = sb.events(match_id=22912)

# Extraer lista de jugadores con su equipo
jugadores = eventos[['player', 'team']].dropna().drop_duplicates().sort_values('team')
print(jugadores.to_string())

def mapa_calor(eventos, jugador, ax):
    datos = eventos[eventos['player'] == jugador].copy()
    datos = datos[datos['location'].notna()]
    datos['x'] = datos['location'].apply(lambda l: l[0])
    datos['y'] = datos['location'].apply(lambda l: l[1])

    pitch = Pitch(pitch_type='statsbomb', pitch_color='#1a1a2e', line_color='white')
    pitch.draw(ax=ax)

    if len(datos) > 5:
        pitch.kdeplot(datos['x'], datos['y'], ax=ax,
                      cmap='YlOrRd', fill=True, alpha=0.7, levels=15)

    pitch.scatter(datos['x'], datos['y'], ax=ax,
                  s=15, color='white', alpha=0.3, zorder=3)

    ax.set_title(f'Mapa de calor — {jugador}', color='white', fontsize=11, fontweight='bold')
    ax.set_facecolor('#1a1a2e')

# Probar con Salah
fig, ax = plt.subplots(figsize=(10, 7))
fig.patch.set_facecolor('#1a1a2e')
mapa_calor(eventos, 'Mohamed Salah', ax)
plt.tight_layout()
plt.show()
print("OK")

# Lista de jugadores únicos
lista_jugadores = eventos[['player', 'team']].dropna().drop_duplicates().sort_values('team')

# Iterar sobre cada jugador
for _, fila in lista_jugadores.iterrows():
    jugador = fila['player']
    equipo = fila['team']

    fig, ax = plt.subplots(figsize=(10, 7))
    fig.patch.set_facecolor('#1a1a2e')
    mapa_calor(eventos, jugador, ax)
    ax.set_title(f'Mapa de calor — {jugador} ({equipo})', color='white', fontsize=11, fontweight='bold')
    plt.tight_layout()
    plt.show()
    print(f"Jugador: {jugador} | Equipo: {equipo}")

def mapa_pases(eventos, jugador, ax):
    datos = eventos[
        (eventos['player'] == jugador) &
        (eventos['type'] == 'Pass')
    ].copy()

    if len(datos) == 0:
        ax.set_title(f'Sin pases — {jugador}', color='white', fontsize=11)
        ax.set_facecolor('#1a1a2e')
        return

    # Extraer coordenadas origen y destino
    datos['x'] = datos['location'].apply(lambda l: l[0])
    datos['y'] = datos['location'].apply(lambda l: l[1])
    datos['x_end'] = datos['pass_end_location'].apply(lambda l: l[0] if isinstance(l, list) else None)
    datos['y_end'] = datos['pass_end_location'].apply(lambda l: l[1] if isinstance(l, list) else None)
    datos = datos.dropna(subset=['x_end', 'y_end'])

    # Separar completados vs fallados
    completados = datos[datos['pass_outcome'].isna()]
    fallados = datos[datos['pass_outcome'].notna()]

    pitch = Pitch(pitch_type='statsbomb', pitch_color='#1a1a2e', line_color='white')
    pitch.draw(ax=ax)

    # Dibujar pases
    pitch.arrows(completados['x'], completados['y'],
                 completados['x_end'], completados['y_end'],
                 ax=ax, color='#1DB954', width=1.5, alpha=0.6, label='Completado')

    pitch.arrows(fallados['x'], fallados['y'],
                 fallados['x_end'], fallados['y_end'],
                 ax=ax, color='#E24B4A', width=1.5, alpha=0.6, label='Fallado')

    total = len(datos)
    pct = round(len(completados) / total * 100) if total > 0 else 0
    ax.set_title(f'Pases — {jugador} | {len(completados)}/{total} completados ({pct}%)',
                 color='white', fontsize=11, fontweight='bold')
    ax.set_facecolor('#1a1a2e')

# Probar con Salah
fig, ax = plt.subplots(figsize=(10, 7))
fig.patch.set_facecolor('#1a1a2e')
mapa_pases(eventos, 'Mohamed Salah', ax)
plt.tight_layout()
plt.show()
print("OK")

def mapa_tiros(eventos, jugador, ax):
    datos = eventos[
        (eventos['player'] == jugador) &
        (eventos['type'] == 'Shot')
    ].copy()

    pitch = Pitch(pitch_type='statsbomb', pitch_color='#1a1a2e', line_color='white')
    pitch.draw(ax=ax)

    if len(datos) == 0:
        ax.set_title(f'Sin tiros — {jugador}', color='white', fontsize=11)
        ax.set_facecolor('#1a1a2e')
        return

    datos['x'] = datos['location'].apply(lambda l: l[0])
    datos['y'] = datos['location'].apply(lambda l: l[1])
    datos['xg'] = datos['shot_statsbomb_xg'].fillna(0)
    datos['gol'] = datos['shot_outcome'].apply(lambda x: x == 'Goal' if isinstance(x, str) else False)

    # Tiros sin gol
    no_gol = datos[~datos['gol']]
    pitch.scatter(no_gol['x'], no_gol['y'], ax=ax,
                  s=no_gol['xg'] * 800 + 50,
                  color='#378ADD', alpha=0.7, zorder=3, label='Tiro')

    # Goles
    goles = datos[datos['gol']]
    pitch.scatter(goles['x'], goles['y'], ax=ax,
                  s=goles['xg'] * 800 + 100,
                  color='#1DB954', alpha=1, zorder=4,
                  marker='*', label='Gol')

    xg_total = round(datos['xg'].sum(), 2)
    goles_total = datos['gol'].sum()
    ax.set_title(f'Tiros — {jugador} | {goles_total} gol(es) · xG: {xg_total}',
                 color='white', fontsize=11, fontweight='bold')
    ax.set_facecolor('#1a1a2e')

# Probar con Salah
fig, ax = plt.subplots(figsize=(10, 7))
fig.patch.set_facecolor('#1a1a2e')
mapa_tiros(eventos, 'Mohamed Salah', ax)
plt.tight_layout()
plt.show()
print("OK")

def stats_resumen(eventos, jugador):
    datos = eventos[eventos['player'] == jugador].copy()

    # Calcular stats
    toques = len(datos[datos['type'] == 'Ball Receipt*'])

    pases = datos[datos['type'] == 'Pass']
    pases_completados = pases[pases['pass_outcome'].isna()]
    pct_pases = round(len(pases_completados) / len(pases) * 100) if len(pases) > 0 else 0

    tiros = datos[datos['type'] == 'Shot']
    goles = tiros[tiros['shot_outcome'] == 'Goal']
    xg = round(tiros['shot_statsbomb_xg'].sum(), 2) if len(tiros) > 0 else 0

    duelos = datos[datos['type'] == 'Duel']
    duelos_ganados = duelos[duelos['duel_outcome'].isin(['Won', 'Success'])] if len(duelos) > 0 else pd.DataFrame()

    presiones = len(datos[datos['type'] == 'Pressure'])
    recuperaciones = len(datos[datos['type'] == 'Ball Recovery'])

    stats = {
        'Toques': toques,
        'Pases': f"{len(pases_completados)}/{len(pases)} ({pct_pases}%)",
        'Tiros': len(tiros),
        'Goles': len(goles),
        'xG': xg,
        'Duelos': f"{len(duelos_ganados)}/{len(duelos)}",
        'Presiones': presiones,
        'Recuperaciones': recuperaciones,
    }
    return stats

# Probar con Salah
stats = stats_resumen(eventos, 'Mohamed Salah')
for k, v in stats.items():
    print(f"{k}: {v}")

def reporte_jugador(eventos, jugador, equipo):
    fig = plt.figure(figsize=(18, 12))
    fig.patch.set_facecolor('#1a1a2e')

    # Titulo principal
    fig.suptitle(f'{jugador}  ·  {equipo}\nFinal Champions League 2019 — Liverpool vs Tottenham',
                 color='white', fontsize=15, fontweight='bold', y=0.98)

    # Layout: 2 filas, 3 columnas
    ax1 = fig.add_subplot(2, 3, 1)  # Mapa de calor
    ax2 = fig.add_subplot(2, 3, 2)  # Mapa de pases
    ax3 = fig.add_subplot(2, 3, 3)  # Mapa de tiros
    ax4 = fig.add_subplot(2, 1, 2)  # Stats resumen

    # Aplicar funciones
    mapa_calor(eventos, jugador, ax1)
    mapa_pases(eventos, jugador, ax2)
    mapa_tiros(eventos, jugador, ax3)

    # Stats resumen como tabla
    stats = stats_resumen(eventos, jugador)
    ax4.set_facecolor('#0d0d1a')
    ax4.axis('off')

    cols = list(stats.keys())
    vals = [str(v) for v in stats.values()]

    tabla = ax4.table(
        cellText=[vals],
        colLabels=cols,
        cellLoc='center',
        loc='center'
    )
    tabla.auto_set_font_size(False)
    tabla.set_fontsize(11)
    tabla.scale(1, 2.5)

    for (row, col), cell in tabla.get_celld().items():
        cell.set_facecolor('#1a1a2e' if row == 0 else '#0d0d1a')
        cell.set_text_props(color='white', fontweight='bold' if row == 0 else 'normal')
        cell.set_edgecolor('#333355')

    plt.tight_layout()
    plt.savefig(f'reporte_{jugador.replace(" ", "_")}.png', dpi=120,
                bbox_inches='tight', facecolor='#1a1a2e')
    plt.show()
    print(f"Reporte generado: {jugador}")

# Probar con Salah
reporte_jugador(eventos, 'Mohamed Salah', 'Liverpool')

for _, fila in lista_jugadores.iterrows():
    reporte_jugador(eventos, fila['player'], fila['team'])